name: Check my code

on: [push,pull_request]

jobs:
  call-checkmycode:
    uses: ncmsdev/numo-builder/.github/workflows/checkmycode.yml@main
    secrets:
      ORG_NPM_INSTALL: ${{ secrets.ORG_NPM_INSTALL }}

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependncies
        run:  sudo npm install
      
      - name: BMS monitor
        run: npx mocha
